pipeline {
	agent { node { label 'toplyvo-dev' } }
	options {
		skipDefaultCheckout true
	}
	stages {
		stage ('Checkout') {
			steps {
				script {
					def specificCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
					def user = specificCause ? specificCause.userName : '-'
	                buildDescription "Started by ${user}"
					try {
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/dev']],
							doGenerateSubmoduleConfigurations: false,
							extensions: [],
							submoduleCfg: [],
							userRemoteConfigs: [[
								credentialsId: '7303d04c-541b-49a3-83f2-834b64810cc5',
								url: 'git@github.com:transloyd/b2b.desktop.api.git'
							]]
						])
					} catch (exc) {}
				}
			}
		}

		stage ('Apply changes') {
			steps {
				script {
						sh "cp .env.dist .env"
						sh "docker-compose up -d --force-recreate --remove-orphans --build"
						withCredentials([string(credentialsId: 'teams_channel_dev_team', variable: 'URL')]) {
							try {
								sh 'curl --retry 5 -H \'Content-Type: application/json\' -d \'{"text": "B2B-desktop (dev) was deployed"}\' $URL'
							} catch (e){}
						}
				}
			}
		}
	}
}
