pipeline {
	agent { node { label 'master' } }
	options {
		skipDefaultCheckout true
	}
	environment {
		DOCKER_USERNAME='jenkins'
        DOCKER_PASSWORD='ch1qySOXu8Q'
        DOCKER_REGISTRY='registry.digitalocean.com/jf-toplyvo'
    }
	stages {

		stage ('Checkout from git') {

			steps {
				script {
					def specificCause = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')
					def user = specificCause ? specificCause.userName : '-'
					buildDescription "Started by ${user}"
					try {
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/stage']],
							doGenerateSubmoduleConfigurations: false,
							extensions: [],
							submoduleCfg: [],
							userRemoteConfigs: [[
								credentialsId: '7303d04c-541b-49a3-83f2-834b64810cc5',
								url: 'git@github.com:transloyd/core.toplyvo.app.git'
							]]
						])
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
					}
				}
			}
		}

		stage ('Login to Registry') {
			steps {
				script {
	                //sh "docker login $DOCKER_REGISTRY -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD"
	                sh "doctl registry login"
                }

			}
		}

		stage ('Remove previous builds') {
			steps {
				script {
					try {
                        sh "docker rmi -f \$(docker images -q --filter 'before=${DOCKER_REGISTRY}/stage_toplyvo_php_fpm' --filter=reference='${DOCKER_REGISTRY}/*')"
					} catch (exc) {}
                }

			}
		}

		stage ('Build pure php image') {
			steps {
				script {
					try {
						sh "rm -R environments"
					} catch (exc) {}

					sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
						sh "git clone git@github.com:transloyd/environments.git"
					}

					sh "cp docker/build/docker-compose.stage_build.yml docker-compose.yml"

					sh "cp .env.dev .env"

					sh "docker-compose build --parallel stage-php-fpm-image stage-php-cli-image"

					sh "docker tag $DOCKER_REGISTRY/stage-php-fpm-image $DOCKER_REGISTRY/stage-php-fpm-image"
					sh "docker push $DOCKER_REGISTRY/stage-php-fpm-image"

					sh "docker tag $DOCKER_REGISTRY/stage-php-cli-image $DOCKER_REGISTRY/stage-php-cli-image"
					sh "docker push $DOCKER_REGISTRY/stage-php-cli-image"
				}
			}
		}

		stage ('PHP preparations') {
			steps {
				script {
					def reqDirs = "var/cache var/logs var/spool var/sessions web/public/img/uploads"
					def envs = "-e REDIS_HOST=test_toplivo_back_redis -e RABBITMQ_HOST=test_toplyvo_rabbitmq -e DATABASE_HOST=test_toplyvo_mysql -e SHELL_DATABASE_HOST='' -e SHELL_DATABASE_PORT=''"
	                sh "docker-compose down"
	                sh "docker-compose up -d composer redis rabbitmq mysql"
	                sh "docker-compose exec -T composer composer install --no-scripts --no-dev"
	                sh "docker-compose exec -T composer composer dump-autoload --classmap-authoritative"
	                sh "docker-compose exec -T composer mkdir -p ${reqDirs}"
	                sh "docker-compose run --rm ${envs} -T composer php bin/console cache:clear --env=prod"
	                sh "docker-compose run --rm ${envs} -T composer php bin/console cache:warmup --env=prod"
	                sh "docker-compose run --rm ${envs} -T composer php bin/console assets:install --env=prod"
	                sh "docker-compose down"
                }

			}
		}

		stage ('Build production php') {
			steps {
				script {
	                sh "docker-compose build --parallel php-fpm php-cron php-consumer"

	                sh "docker tag $DOCKER_REGISTRY/stage_toplyvo_php_fpm $DOCKER_REGISTRY/stage_toplyvo_php_fpm"
                    sh "docker push $DOCKER_REGISTRY/stage_toplyvo_php_fpm"

                    sh "docker tag $DOCKER_REGISTRY/stage_toplyvo_php_cron $DOCKER_REGISTRY/stage_toplyvo_php_cron"
                    sh "docker push $DOCKER_REGISTRY/stage_toplyvo_php_cron"

                    sh "docker tag $DOCKER_REGISTRY/stage_toplyvo_php_consumer $DOCKER_REGISTRY/stage_toplyvo_php_consumer"
                    sh "docker push $DOCKER_REGISTRY/stage_toplyvo_php_consumer"
                }

			}
		}

		stage ('Build production nginx') {
			steps {
				script {
	                sh "docker-compose build nginx"
	                sh "docker tag $DOCKER_REGISTRY/stage_toplyvo_nginx $DOCKER_REGISTRY/stage_toplyvo_nginx"
	                sh "docker push $DOCKER_REGISTRY/stage_toplyvo_nginx"
                }

			}
		}

		stage ('Logout from Registry') {
			steps {
				script {
	                //sh "docker logout $DOCKER_REGISTRY"
	                sh "doctl registry logout"
                }

			}
		}

		stage ('Run B2C deploy (stage)') {
			steps {
				script {
	                build wait: false, job: 'B2C deploy (stage)'
                }

			}
		}

	}
}
