import groovy.transform.Field
@Field
def REPOSITORIES = ['core.toplyvo.app','toplyvotransporter','toplyvodesktop','toplyvosmsauth','insurance']

pipeline {
	agent { node { label 'master' } }
	options {
		skipDefaultCheckout true
	}
	stages {
		stage('Comparing branches') {
			steps {
				script {
					cleanWs()
					def description = '';
					def teamsNotif = 'Current difference between branches<br/>';
					try {
						REPOSITORIES.each {value ->
							checkout([
								$class: 'GitSCM',
								branches: [[name: '*/stage']],
								doGenerateSubmoduleConfigurations: false,
								extensions: [[
									$class: 'RelativeTargetDirectory',
									relativeTargetDir: "${value}"
								]],
								submoduleCfg: [],
								userRemoteConfigs: [[
									credentialsId: '7303d04c-541b-49a3-83f2-834b64810cc5',
									url: "git@github.com:transloyd/${value}.git"
								]]
							])
							dir("${value}") {
								def devStageDiff = sh (
									script: "git log origin/stage...origin/develop | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | print \$0 ",
									returnStdout: true
								)
								echo "${value}: develop -> stage\n${devStageDiff}\n"
								if(devStageDiff!='') {
									description = description+ "${value}: develop -> stage\n${devStageDiff}\n"
									teamsNotif = teamsNotif+ "${value}: develop -> stage<br/>${devStageDiff}<br/>"
								}

								def masterStageDiff = sh (
									script: "git log origin/master...origin/stage | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | print \$0 ",
									returnStdout: true
								)
								echo "${value}: stage -> master\n${masterStageDiff}\n"
								if(masterStageDiff!='') {
									description = description + "${value}: stage -> master\n${masterStageDiff}\n"
									teamsNotif = teamsNotif + "${value}: stage -> master<br/>${masterStageDiff}<br/>"
								}
							}
						}

					} catch (exc) {}
					buildDescription description
					sh "curl -H 'Content-Type: application/json' -d '{\"text\": \"${teamsNotif}\"}' https://outlook.office.com/webhook/48bc9880-4b14-45b3-9ee3-93d0be4bd4f1@ef26001e-365b-4295-8511-2417ac86a68b/IncomingWebhook/662cfe3708cc4d769f4e5b268e9696c7/01797945-d308-43e9-b9c8-d9ed3f116bcf"
					cleanWs()
				}
			}
		}
	}
}
