node {
	sh "rm -R environments"
	sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
		sh "git clone git@github.com:transloyd/environments.git"
	}
// this part needed only for first generate parameters to job
/*
	def props = readProperties file: "environments/b2c/.env.app"
	dynamicParams = []
	params.each {key, value ->
		dynamicParams += [
            string(name: "$key", defaultValue: "$value", description: ''),
        ]
    }
	props.each { key, value ->
		dynamicParams += [
            string(name: "$key", defaultValue: "$value", description: ''),
        ]
	}
	properties([
        parameters(dynamicParams)
    ])
*/
}

pipeline {
	agent any

    stages {
        stage ('Update .env') {
            steps {
                script {
                    dir('environments/b2c/') {
	                    def envFile = ".env.app"
	                  /*  def props = writeFile file: "${envFile}", text: ''
						params.each {key, value ->
							sh "echo ${key}=${value} >> ${envFile}"
						}
						sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
							sh "git commit ${envFile} -m 'Pipeline update env'"
							sh "git push"
						}
*/
						ENV = readFile file: envFile
					}
				}
			}
        }
    }
}

node ('toplivo-test-ssh-deploy') {
sh 'ls'
	ws('Test prod deploy from registry') {
		sh 'ls'
		println ENV
	}
}

node {
	def props = readProperties file: "environments/b2c/.env.app"
	dynamicParams = []
	props.each { key, value ->
		dynamicParams += [
            string(name: "$key", defaultValue: "$value", description: ''),
        ]
	}
	properties([
        parameters(dynamicParams)
    ])
}