node {
	sh 'git reset --hard HEAD'
	def WORKSPACE = pwd()
	def props = readProperties file: "${WORKSPACE}/prod/environment/.properties"
	dynamicParams = []
	props.each { key, value ->
		dynamicParams += [
            string(name: "$key", defaultValue: "$value", description: ''),
        ]
	}
	properties([
        parameters(dynamicParams)
    ])
}

pipeline {
	agent any

    stages {
        stage ('Update .env') {
            steps {
                script {
                    def WORKSPACE = pwd()
                    def envFile = "prod/environment/.properties"
                    def props = writeFile file: "${envFile}", text: ''
					params.each {key, value ->
						sh "echo ${key}=${value} >> ${envFile}"
					}
				}
			}
        }
    }
}
