env.RUN_ENV = 'test'
env.NGINX_EXPOSE_PORT = '8089'
env.CONTAINER_NAME_PREFIX = 'deploy_dev_n3'
env.APP_RANDOM_GENERATOR_END = 111111
env.APP_LIQPAY_PAY_STATUS = 'sandbox'
env.APP_LIQPAY_PAY_SANDBOX = 1
env.SYMFONY_ENV= 'dev'
env.NGINX_ENV='test'
env.APP_SMS_TRANSPORT="void"
env.INTEGRATION_DEFAULT_SHELL_CABINET=10
env.APP_WOG_ID=4
env.APP_WOG_CABINET_ID=17
env.APP_CDN_CACHE_REGION='fra1'
env.APP_CDN_CACHE_KEY='I6RRI4TFOIE42C5ND7CA'
env.APP_CDN_CACHE_SECRET='iREShApsf+FCjKXdmJnHWwsg+cc6IVELSjzAhX9J9lc'
env.APP_CDN_CACHE_BUCKET='toplyvo-stage'
env.APP_CACHE_CLEAR_BASE_URI='https://toplyvo.branderstudio.com'
env.APPSFLYER_SDK_KEY='RMg76uUfMecAQoAjWzRyni'
env.APPSFLYER_API_KEY='9c9a9295-e697-47e0-80d2-dcfe26fc8889'
env.FIREBASE_DYNAMIC_LINKS_TOKEN='AIzaSyCGCQJtAUp9PlZW9JaRtD686OksvjV6hRU'
env.APP_INTEGRATION_TOKEN_BVS='d5d151b61e59b98560cc6097b7faf1447c300bffe0d9172eebd873b5cf6c5f86'
env.APP_APPLE_PAY_PASSWORD='password_toplivo_98'
env.INTEGRATION_DEFAULT_BVS_CABINET=18
env.REDIS_HOST='10.135.218.123'//deploy_dev_n3_toplivo_back_redis
env.APP_SERVER='test'
env.APP_AUTH_CODE_LIFETIME='1 minutes'
env.APP_AUTH_CODE_MAX_PER_DAY='5'
env.APP_AUTH_CODE_TIME_BETWEEN_CODE='1 minutes'
env.APP_AUTH_RETRIES_MAX_ALLOWED=5
env.MYSQL_DATABASE_HOST='deploy_dev_n3_toplivo_back_mysql'
env.MYSQL_EXPOSE_PORT='3434'
env.MYSQL_ROOT_PASSWORD='7s6fHJ7G55RDs2'
env.MYSQL_DATABASE='toplyvo'
env.MYSQL_USER='toplyvo_user'
env.MYSQL_PASSWORD='oj57HG8jHG76'
env.API_TRANSPORTER_URL='http://toplyvo_transporter_nginx'
env.INTEGRATION_DEFAULT_USER_PHONE='+380500000000'
env.PORTMONE_PASSWORD=11111111
env.APP_NOTIFY_CLIENT_WITHOUT_ORDERS_FROM='12:00:00'
env.DOCKER_USERNAME='jenkins'
env.DOCKER_PASSWORD='ch1qySOXu8Q'
env.HOST='jenkins@toplyvo.branderstudio.com'
env.HOST_WORKDIR='/home/jenkins/workspace/toplivo.backend.deploy.dev.n3'
env.ROADS_TRANSLOYD_BASE_URI='https://e-toll.dev.topy.toplyvo.app'
env.TRACKING_DATABASE_HOST='deploy_dev_n3_toplivo_back_mysql'
env.TRACKING_DATABASE_NAME='toplyvo_tracking'
env.TRACKING_DATABASE_USER='toplyvo_tracking_user'
env.TRACKING_DATABASE_PASSWORD='ok23HJ78W6h'
env.APP_REGISTRATION_GIFT_FUEL_NETWORK_TYPE='wog'
env.BNK_SECRET='73fc6927-eb46-48a3-a19c-6b10023e6626'
env.ONLINE_FUELING_IOS_BUILD=202002280000
env.APP_ORDER_FREE_PURCHASE_FOR_EVERY=10
env.APP_INTEGRATION_TOKEN_SUNOIL='278c8479d5ad823cf478eb918ed7eb2039c7ddbd9d34bd3b3f01bdced41edd02'
env.REDIS_HOST2='10.135.218.123'
env.REDIS_HOST3='10.135.218.123'

pipeline {
   agent any
    environment {
        BRANCH = 'TPLV-950'
        }
      stages {
            stage ('checkout ci') {
                steps {
                    git branch: BRANCH,
                    credentialsId: '9c9f9f44-ba94-4a76-901e-433187342316',
                    url: 'git@github.com:transloyd/core.toplyvo.app.git'
                    sh "ls -lat"
                }
            }
            stage ('docker build&push') {
                steps  {
                    sh "cp .env.stage .env"
                    sh "docker-compose build instantclient"
                    sh "docker-compose build php php_consumer php_cli"
                    sh "docker login https://jf.toplyvo.app -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD"
                    sh "docker tag toplivobackenddeploydev_php jf.toplyvo.app/toplivobackenddeploydev_n3_php"
                    sh "docker push jf.toplyvo.app/toplivobackenddeploydev_n3_php"
                    sh "docker tag toplivobackenddeploydev_php_consumer jf.toplyvo.app/toplivobackenddeploydev_n3_php_consumer"
                    sh "docker push jf.toplyvo.app/toplivobackenddeploydev_n3_php_consumer"
                    sh "docker tag toplivobackenddeploydev_php_cli jf.toplyvo.app/toplivobackenddeploydev_n3_php_cli"
                    sh "docker push jf.toplyvo.app/toplivobackenddeploydev_n3_php_cli"
                    sh "docker tag instantclient_files jf.toplyvo.app/instantclient_files"
                    sh "docker push jf.toplyvo.app/instantclient_files"
                    sh "docker logout https://jf.toplyvo.app"
                    }
                }
        }
    }
node ('toplivo-dev-ssh-deploy') {
    def BRANCH = 'TPLV-950'
    stage ('chekout host') {
            git branch: BRANCH,
            credentialsId: '9c9f9f44-ba94-4a76-901e-433187342316',
            url: 'git@github.com:transloyd/core.toplyvo.app.git'
        }
    stage ('deploy') {
            sh "cp /home/jenkins/ci/.env .env"
            //sh "cp .env.stage .env"
            //sh "cp /home/jenkins/web/docker-compose.yml ."
            sh "cp /home/jenkins/ci/docker-compose_n3.yml docker-compose.yml"
            sh "cp /home/jenkins/ci/varnish/nginx/toplivo_test.conf ./docker/varnish/nginx/toplivo_test.conf"
            sh "docker-compose stop nginx"
            //sh "sed -i \"s/app_dev/app/g\" docker/nginx/toplivo_test.conf"
            sh "sed -i \"s/dev_toplivo_back_nginx/${CONTAINER_NAME_PREFIX}_toplivo_back_nginx/g\" docker/varnish/varnish/default.vcl"
            sh "sed -i \"s/dev_/dev_n3_/g\" docker/varnish/nginx/toplivo_test.conf"
            sh "cat docker/varnish/varnish/default.vcl"
            sh 'docker login https://jf.toplyvo.app -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD'
            sh "docker-compose build mysql"
            sh "docker-compose up -d mysql"
            sh "docker rm -f ${CONTAINER_NAME_PREFIX}_toplivo_back_varnish"
            sh "docker-compose pull instantclient"
            sh "docker-compose pull php php_consumer php_cli"
            sh 'docker logout https://jf.toplyvo.app'
            sh "docker-compose up --no-deps -d nginx"
            sh "docker-compose up --no-deps -d varnish"
            sh "docker-compose up --no-deps -d varnish_nginx"
            sh "docker-compose up --no-deps --force-recreate -d php php_consumer php_cli oracle_stunnel"
            sh "docker-compose up --no-deps -d rabbitmq"
            sh "docker-compose up --no-deps -d redis"
            sh "docker-compose up --no-deps -d centrifugo"
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_nginx nginx -s reload"
            sh "docker cp ./docker/php/parameters.yml.dist ${CONTAINER_NAME_PREFIX}_toplivo_back_php:/var/www/html/app/config/parameters.yml"
            sh "docker exec --user www-data ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console doctrine:cache:clear-metadata\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"cd /var/www/html && composer install\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_nginx /bin/bash -c \"chmod -R 777 /var/www/html/var/*\""
            sh "docker exec --user www-data ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console doctrine:cache:clear-metadata\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console --configuration=./app/config/doctrine/migrations.yml doctrine:migrations:migrate  --allow-no-migration --no-interaction --no-debug\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console --em=tracking --configuration=./app/config/doctrine/tracking_migrations.yml doctrine:migrations:migrate --allow-no-migration --no-interaction --no-debug\""
            sh "docker exec --user www-data ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console doctrine:cache:clear-metadata\""
            sh "docker exec --user www-data ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"php bin/console cache:clear\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_nginx /bin/bash -c \"chmod -R 777 /var/www/html/var/*\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"chmod -R 777 ./web/public/files\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"chmod -R 777 ./web/public/img/uploads\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"chown -R www-data:www-data ./web/media\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php /bin/bash -c \"chown -R www-data:www-data ./var/\""
            sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php_cli /bin/bash -c \"/bin/bash /entrypoint.sh\""
           //sh "docker exec ${CONTAINER_NAME_PREFIX}_toplivo_back_php_consumer /bin/bash -c \"php bin/console rabbitmq-supervisor:rebuild\""
            sh "sleep 5"
            //sh "docker exec -itd ${CONTAINER_NAME_PREFIX}_toplivo_back_php_consumer /bin/bash -c \"php bin/console rabbitmq-supervisor:control start --wait-for-supervisord\""
        }
}
