node ('master') {
	dir ("/var/lib/jenkins/workspace/B2C image builder (prod)") {
		sh 'ls -la docker'
		stash name: "docker", includes: "docker/", allowEmpty: true
	}
}

pipeline {
	agent { node { label 'toplivo-production-ssh' } }
	options {
		skipDefaultCheckout true
	}
	environment {
		def DOCKER_USERNAME='jenkins'
        def DOCKER_PASSWORD='ch1qySOXu8Q'
        def DOCKER_REGISTRY='jf-dev.toplyvo.app'
    }
	parameters {
        gitParameter name: 'TAG',
                     type: 'PT_TAG',
                     defaultValue: 'v2.0.0',
                     description: 'Tag og docker image\'s build',
                     quickFilterEnabled: true,
                     sortMode: 'DESCENDING_SMART',
                     useRepository: 'git@github.com:transloyd/core.toplyvo.app.git'

    }
	stages {

		stage ('Get build configuration') {
			steps {
				buildDescription "${params.TAG}"
				sh "git init"
				sh "git remote add origin git@github.com:transloyd/core.toplyvo.app.git"
				script { try {
					sh 'rm -R *'
				} catch (exc) {}}
				unstash "docker"
			}
		}

		stage ('Login to Registry') {
			steps {
				script {
	                sh "docker login $DOCKER_REGISTRY -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD"
                }

			}
		}

		stage ('Apply builds') {
			environment {
				IMAGE_TAG="${params.TAG}"
			}
			steps {
				script {
					try {
						sh "rm -R environments"
					} catch (exc) {}

					sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
						sh "git clone git@github.com:transloyd/environments.git"
					}

					sh "cp docker/build/docker-compose.prod.yml docker-compose.yml"

					sh "cp environments/b2c/.env .env"

					sh "docker pull ${DOCKER_REGISTRY}/prod_toplyvo_php_fpm:${params.TAG}"
					sh "docker pull ${DOCKER_REGISTRY}/prod_toplyvo_php_consumer:${params.TAG}"
					sh "docker pull ${DOCKER_REGISTRY}/prod_toplyvo_php_cli:${params.TAG}"
					sh "docker pull ${DOCKER_REGISTRY}/prod_toplyvo_nginx:${params.TAG}"

/*
					sh "docker-compose up -d --force-recreate php"
					sh "docker-compose up -d --force-recreate php_cli"
					sh "docker-compose run php_cli php bin/console --configuration=./app/config/doctrine/migrations.yml doctrine:migrations:migrate --env=prod"

					sh "docker-compose up -d --remove-orphans"
*/
				}
			}
		}

		stage ('Logout from Registry') {
			steps {
				script {
	                sh "docker logout $DOCKER_REGISTRY"
                }

			}
		}

	}
}