pipeline {
	agent { node { label 'test-Toplyvo-core-Mayatskiy' } }
	environment {
		def DOCKER_USERNAME='jenkins'
        def DOCKER_PASSWORD='ch1qySOXu8Q'
        def DOCKER_HOST='jf-dev.toplyvo.app'
    }
	stages {

		stage ('Checkout from git') {

			steps {
				script {
					try {
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/TPLV-846']],
							doGenerateSubmoduleConfigurations: false,
							extensions: [],
							submoduleCfg: [],
							userRemoteConfigs: [[
								credentialsId: '7303d04c-541b-49a3-83f2-834b64810cc5',
								url: 'git@github.com:transloyd/core.toplyvo.app.git'
							]]
						])
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
						currentStage.result = 'FAILURE'
					}
				}
			}
		}

		stage ('Login to Registry') {
			steps {
				script {
	                //sh "docker login $DOCKER_HOST -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD"
	                //sh "docker tag testprodbuildimage_php $DOCKER_HOST/testprodbuildimage_php:2.10"
	                //sh "docker push $DOCKER_HOST/testprodbuildimage_php"
	                //sh "docker images"
	                sh "docker logout $DOCKER_HOST"
                }

			}
		}


		stage ('Build php image') {
			steps {
				script {
					sh "docker logout $DOCKER_HOST"
					sh "cp docker-compose.prod.yml docker-compose.yml"
					sh "cp .env.dev .env"
					sh "docker-compose build"
				}
			}
		}

		stage ('Logout from Registry') {
			steps {
				script {
	                sh "docker logout $DOCKER_HOST"
                }

			}
		}

	}
}