pipeline {
	agent { node { label 'test-Toplyvo-core-Mayatskiy' } }

	stages {

		stage ('Checkout from git') {

			steps {

				checkout([
					$class: 'GitSCM',
					branches: [[name: '*/TPLV-846']],
					doGenerateSubmoduleConfigurations: false,
					extensions: [[
					]],
					submoduleCfg: [],
					userRemoteConfigs: [[
						credentialsId: '7303d04c-541b-49a3-83f2-834b64810cc5',
						url: 'git@github.com:transloyd/toplyvotransporter.git'
					]]
				])

			}
		}

		stage ('Build php image') {
			steps {
				script {
					sh "cp docker-compose.prod.yml docker-compose.yml"
					sh "docker-compose build"
				}
			}
		}
	}
}