node ('toplivo-production-ssh') {
    stage ('clear') {
            sh "redis-cli -h 167.71.43.0 flushall async"
            sh "redis-cli -h 167.71.43.0 flushall async"
            sh "redis-cli -h 167.71.43.0 flushall async"

    }
}
