import groovy.transform.Field
@Field
def Dev = [id:'10107']
@Field
def Stage = [id:'10108']
@Field
def Prod = [id:'10109']
@Field
def Local = [id:'10106']
// Create release to stage
def VERSION_TAG = "v${env.Release}"
def sourceBranch = env.HOTFIX.toBoolean() ? 'hotfix' :'stage'
def masterStageDiff = '';
def logs = '';
pipeline {
	agent any
	options {
		skipDefaultCheckout true
	}
	parameters{
		string(name: "Release", defaultValue: Release, description: '')
	}
	stages {

		stage ('Checkout master') {

			steps {
				script {
					def postfix = env.HOTFIX.toBoolean() ? ' HOTFIX' : ''
					buildDescription "${env.Repository}\n${VERSION_TAG} ${postfix}"

					try {
						sh "rm -R *"
						sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
							sh "git config --global user.email 'develop@toplyvo.app'"
                            sh "git config --global user.name 'Jenkins'"
							sh "git clone git@github.com:transloyd/${env.Repository}.git"
						}

						dir("${env.Repository}") {
							sh "git checkout master"
						}
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
					}
				}

			}
		}

		stage ('Check tag') {
			steps {
				script {
					try {
						dir("${env.Repository}") {
							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
								sh "git fetch --tags"

								def isGitTagExists = sh(returnStdout: true, script: "git tag -l '${VERSION_TAG}'").trim()

								if (isGitTagExists) {
									echo "Tag ${VERSION_TAG} is already exists"
									error("Tag ${VERSION_TAG} is already exists")
								}
	                        }
                        }
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
					}

				}
			}
		}

		stage ('Make release merge') {
			steps {

				script {
					try {
						dir("${env.Repository}") {
							masterStageDiff = sh (
								script: "git log origin/master...origin/${sourceBranch} | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | awk '{print \$0\"<br/>\"}' ",
								returnStdout: true
							)
							logs = sh (
								script: "git log origin/master...origin/${sourceBranch} | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | awk '{print \$0}' ",
								returnStdout: true
							).split( '\n' )

							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
								sh "git merge origin/${sourceBranch} --no-ff -m 'Automated release ${VERSION_TAG}. ${env.BUILD_URL}'"

	                            sh "git tag -a ${VERSION_TAG} -m 'Automated Jenkins build #${env.BUILD_ID}'"
								sh "git push --progress origin master --tags"
	                        }
                        }
					}
					catch (exc) {
						echo 'DEBUG: PUSHING error'
						currentBuild.result = 'FAILURE'
					}

					if(masterStageDiff!='') {
						def teamsNotif = "${env.Repository}: MERGED stage -> master<br/>${masterStageDiff}<br/>"
						withCredentials([string(credentialsId: 'teams_channel_dev_team', variable: 'URL')]) {
							try {
								sh 'curl --retry 5 -H \'Content-Type: application/json\' -d \'{"text": "'+teamsNotif+'"}\' $URL'
							} catch (e){
								echo 'DEBUG: TEAMS sending error'
							}
						}
					}
				}

			}
		}

		stage ('Synchronize hotfix branch') {
			when {
				expression {!env.HOTFIX.toBoolean()}
			}
			steps {

				script {
					try {
						dir("${env.Repository}") {
							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
	                            sh "git checkout hotfix"

								sh "git merge origin/master --no-ff"
								sh "git push --progress origin hotfix"
	                        }
                        }
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
					}

				}

			}
		}

		stage('Set Jira env') {
			steps {
				script {
					echo "DEBUG: logs"
					logs.each {value ->
						def issueEnv = [fields: [customfield_10049: Prod/*, assignee: [accountId:'5f23c383ef11df0025a5b003']*/]]
                        jiraEditIssue idOrKey: value, issue: issueEnv, site: 'Jira Toplyvo'
                    }
				}
			}
		}

	}

}
