import groovy.transform.Field
@Field
def Dev = [id:'10107']
@Field
def Stage = [id:'10108']
@Field
def Prod = [id:'10109']
@Field
def Local = [id:'10106']
// Create release to stage
def VERSION_TAG = "v${env.Release}"
def sourceBranch = env.HOTFIX.toBoolean() ? 'hotfix' :'stage'
pipeline {
	agent any
	options {
		skipDefaultCheckout true
	}
	parameters{
		string(name: "Release", defaultValue: Release, description: '')
	}
	stages {

		stage ('Checkout master') {

			steps {
				script {
					def postfix = env.HOTFIX.toBoolean() ? ' HOTFIX' : ''
					buildDescription "${env.Repository}\n${VERSION_TAG} ${postfix}"

					try {
						sh "rm -R *"
						sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
							sh "git config --global user.email 'develop@toplyvo.app'"
                            sh "git config --global user.name 'Jenkins'"
							sh "git clone git@github.com:transloyd/${env.Repository}.git"
						}

						dir("${env.Repository}") {
							sh "git checkout master"
						}
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
						currentStage.result = 'FAILURE'
					}
				}

			}
		}

		stage ('Check tag') {
			steps {
				script {
					try {
						dir("${env.Repository}") {
							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
								sh "git fetch --tags"

								def isGitTagExists = sh(returnStdout: true, script: "git tag -l '${VERSION_TAG}'").trim()

								if (isGitTagExists) {
									echo "Tag ${VERSION_TAG} is already exists"
									error("Tag ${VERSION_TAG} is already exists")
								}
	                        }
                        }
					}
					catch (exc) {
						currentBuild.result = 'FAILURE'
						currentStage.result = 'FAILURE'
					}

				}
			}
		}

		stage ('Make release merge') {
			steps {

				script {
					try {
						dir("${env.Repository}") {
							masterStageDiff = sh (
								script: "git log origin/master...origin/stage | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | awk '{print \$0\"<br/>\"}' ",
								returnStdout: true
							)

							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
								sh "git merge origin/${sourceBranch} --no-ff -m 'Automated release ${VERSION_TAG}. ${env.BUILD_URL}'"

	                            sh "git tag -a ${VERSION_TAG} -m 'Automated Jenkins build #${env.BUILD_ID}'"
								sh "git push --progress origin master --tags"
	                        }

							if(masterStageDiff!='') {
								def teamsNotif = "${value}: MERGED develop -> stage<br/>${devStageDiff}<br/>"
								sh "curl -H 'Content-Type: application/json' -d '{\"text\": \"${teamsNotif}\"}' https://outlook.office.com/webhook/48bc9880-4b14-45b3-9ee3-93d0be4bd4f1@ef26001e-365b-4295-8511-2417ac86a68b/IncomingWebhook/662cfe3708cc4d769f4e5b268e9696c7/01797945-d308-43e9-b9c8-d9ed3f116bcf"
							}
                        }
					}
					catch (exc) {
						sh "git status"
						currentBuild.result = 'FAILURE'
						currentStage.result = 'FAILURE'
					}

				}

			}
		}

		stage ('Synchronize hotfix branch') {
			when {
				expression {!env.HOTFIX.toBoolean()}
			}
			steps {

				script {
					try {
						dir("${env.Repository}") {
							sshagent(['7303d04c-541b-49a3-83f2-834b64810cc5']) {
	                            sh "git checkout hotfix"

								sh "git merge origin/master --no-ff"
								sh "git push --progress origin hotfix"
	                        }
                        }
					}
					catch (exc) {
						sh "git status"
						currentBuild.result = 'FAILURE'
						currentStage.result = 'FAILURE'
					}

				}

			}
		}

		stage('Set Jira env') {
			steps {
				script {
					def logs = sh (
						script: "git log origin/master...origin/stage | grep -e '[A-Z]\\+-[0-9]\\+' -o | sort | uniq | awk '{print \$0}' ",
						returnStdout: true
					).split( '\n' )
					logs.each {value ->
                        jiraEditIssue idOrKey: value, issue: Prod, site: 'Jira Toplyvo'
                    }
				}
			}
		}

	}

}
